# pragma once

#define MEGABYTE           0x100000

#define MEM_KERNEL_START   0x80000
#define KERNEL_MAX_SIZE    (10 * MEGABYTE)
#define MEM_KERNEL_END     (MEM_KERNEL_START + KERNEL_MAX_SIZE)

#define KERNEL_STACK_SIZE  0x20000
#define MEM_KERNEL_STACK   (MEM_KERNEL_END + KERNEL_STACK_SIZE)

